# Getting started with NumPy

In [1]:
import numpy as np

## Getting used to vectorization and broadcasting

First, let's generate some test data. Generate a two-dimensional array with 10 rows and 4 columns, from a normal distribution with mean = 100 and standard deviation 20.

In [2]:
data = 
data

array([[  81.21791578,   72.58976397,  105.04234627,  129.37064597],
       [ 110.28787522,   82.37075999,   82.41293525,   74.66888214],
       [  94.87784966,  140.14690917,  110.20810429,  127.77686892],
       [ 106.34539585,  102.26758466,  110.03036272,  136.74775068],
       [ 134.3294198 ,   97.69758834,  114.29490153,  109.82299198],
       [ 121.91325329,   95.3176566 ,  122.99379858,  111.69982983],
       [ 111.60500245,  106.42323119,   77.36161569,   83.22961653],
       [ 100.70169929,  111.70501412,   91.24326498,   86.64841803],
       [  75.95686274,   99.55455463,  123.83890829,   97.81606041],
       [ 122.14576486,   80.78062252,   93.4670416 ,   80.23398489]])

Round the data to one decimal place.

In [3]:
data = 
data

array([[  81.2,   72.6,  105. ,  129.4],
       [ 110.3,   82.4,   82.4,   74.7],
       [  94.9,  140.1,  110.2,  127.8],
       [ 106.3,  102.3,  110. ,  136.7],
       [ 134.3,   97.7,  114.3,  109.8],
       [ 121.9,   95.3,  123. ,  111.7],
       [ 111.6,  106.4,   77.4,   83.2],
       [ 100.7,  111.7,   91.2,   86.6],
       [  76. ,   99.6,  123.8,   97.8],
       [ 122.1,   80.8,   93.5,   80.2]])

Display the last 2 columns of rows 1-5 (let's agree that we start counting from 1 when using normal language).

array([[ 105. ,  129.4],
       [  82.4,   74.7],
       [ 110.2,  127.8],
       [ 110. ,  136.7],
       [ 114.3,  109.8]])

Now, set all data points > 130 to 0.

In [5]:
data = 
data

array([[  81.2,   72.6,  105. ,  129.4],
       [ 110.3,   82.4,   82.4,   74.7],
       [  94.9,    0. ,  110.2,  127.8],
       [ 106.3,  102.3,  110. ,    0. ],
       [   0. ,   97.7,  114.3,  109.8],
       [ 121.9,   95.3,  123. ,  111.7],
       [ 111.6,  106.4,   77.4,   83.2],
       [ 100.7,  111.7,   91.2,   86.6],
       [  76. ,   99.6,  123.8,   97.8],
       [ 122.1,   80.8,   93.5,   80.2]])

Take the square root of all data points.

In [6]:
data = 
data

array([[  9.01110426,   8.52056336,  10.24695077,  11.37541208],
       [ 10.50238068,   9.07744457,   9.07744457,   8.64291617],
       [  9.7416631 ,   0.        ,  10.49761878,  11.30486621],
       [ 10.31018914,  10.11434625,  10.48808848,   0.        ],
       [  0.        ,   9.88433103,  10.69111781,  10.47854952],
       [ 11.0408333 ,   9.76217189,  11.09053651,  10.56882207],
       [ 10.56409012,  10.31503757,   8.79772698,   9.1214034 ],
       [ 10.03493896,  10.56882207,   9.54986911,   9.3059121 ],
       [  8.71779789,   9.97997996,  11.12654484,   9.88938825],
       [ 11.04988688,   8.98888202,   9.6695398 ,   8.95544527]])

Now, compute the mean and the standard deviation over all data points.

In [7]:
mean, sd = 
mean, sd

(9.2265653943648349, 2.7414395896151467)

Then, compute the row means and standard deviations.

In [8]:
row_ms, row_sds = 
row_ms, row_sds

(array([  9.78850762,   9.3250465 ,   7.88603702,   7.72815597,
          7.76349959,  10.61559094,   9.69956452,   9.86488556,
          9.92842773,   9.66593849]),
 array([ 1.11135891,  0.70250107,  4.58643871,  4.46381063,  4.49200113,
         0.53313126,  0.75395504,  0.48376944,  0.8522457 ,  0.84831188]))

Finally, compute column means and standard deviations.

In [9]:
col_ms, col_sds = 
col_ms, col_sds

(array([  9.09728843,   8.72115787,  10.12354376,   8.96427151]),
 array([ 3.12079207,  2.97008508,  0.7706242 ,  3.12439375]))

Now, compute the mean and standard deviation of column 2 without using NumPy's mean function.

In [10]:
data

array([[  9.01110426,   8.52056336,  10.24695077,  11.37541208],
       [ 10.50238068,   9.07744457,   9.07744457,   8.64291617],
       [  9.7416631 ,   0.        ,  10.49761878,  11.30486621],
       [ 10.31018914,  10.11434625,  10.48808848,   0.        ],
       [  0.        ,   9.88433103,  10.69111781,  10.47854952],
       [ 11.0408333 ,   9.76217189,  11.09053651,  10.56882207],
       [ 10.56409012,  10.31503757,   8.79772698,   9.1214034 ],
       [ 10.03493896,  10.56882207,   9.54986911,   9.3059121 ],
       [  8.71779789,   9.97997996,  11.12654484,   9.88938825],
       [ 11.04988688,   8.98888202,   9.6695398 ,   8.95544527]])

In [11]:
# take just column 2
col2 = 
col2

array([  8.52056336,   9.07744457,   0.        ,  10.11434625,
         9.88433103,   9.76217189,  10.31503757,  10.56882207,
         9.97997996,   8.98888202])

In [12]:
# calculate the mean
mean_col2 = 
mean_col2

8.7211578727462395

In [13]:
# calculate the variance
var_col2 = 
var_col2

8.8214053586362979

In [14]:
# calculate the standard deviation
sd_col2 = 
sd_col2

2.970085075992992

Now double check again using NumPy's mean and std functions.

8.7211578727462395

2.970085075992992

## Linear regression from scratch

For practise with ndarrays and matrix operations, we are going to compute regression coefficients for linear regression ourselves.

First, let's create some data. We have measured 2 variables:

In [21]:
X = np.random.randint(-10,10,(20,2))
X

array([[ 3, -2],
       [-1,  1],
       [ 9,  0],
       [-9, -6],
       [ 3, -4],
       [ 3,  2],
       [ 6,  8],
       [-7,  1],
       [ 3,  4],
       [ 7, -9],
       [ 7, -1],
       [ 6, -3],
       [ 9,  7],
       [-7,  6],
       [-9, -5],
       [-1,  5],
       [-2,  3],
       [ 3, -6],
       [ 5,  4],
       [ 8, -6]])

In [22]:
X[:,1] = X[:,1] * 20 + 2
X

array([[   3,  -38],
       [  -1,   22],
       [   9,    2],
       [  -9, -118],
       [   3,  -78],
       [   3,   42],
       [   6,  162],
       [  -7,   22],
       [   3,   82],
       [   7, -178],
       [   7,  -18],
       [   6,  -58],
       [   9,  142],
       [  -7,  122],
       [  -9,  -98],
       [  -1,  102],
       [  -2,   62],
       [   3, -118],
       [   5,   82],
       [   8, -118]])

We want to predict a target variable y.
Of course, normally y would not be under our control ;-) But here, we are going to cheat ...

In [24]:
y = 30 + 3 * X[:,0] - X[:,1]
y

array([  77,    5,   55,  121,  117,   -3, -114,  -13,  -43,  229,   69,
        106,  -85, -113,  101,  -75,  -38,  157,  -37,  172])

To calculate the regression coefficients, we need to add a column of ones to the input matrix.

In [1]:
ones = np.ones((20,1))
ones

NameError: name 'np' is not defined

In [26]:
X = np.append(ones, X, axis=1)
X

array([[   1.,    3.,  -38.],
       [   1.,   -1.,   22.],
       [   1.,    9.,    2.],
       [   1.,   -9., -118.],
       [   1.,    3.,  -78.],
       [   1.,    3.,   42.],
       [   1.,    6.,  162.],
       [   1.,   -7.,   22.],
       [   1.,    3.,   82.],
       [   1.,    7., -178.],
       [   1.,    7.,  -18.],
       [   1.,    6.,  -58.],
       [   1.,    9.,  142.],
       [   1.,   -7.,  122.],
       [   1.,   -9.,  -98.],
       [   1.,   -1.,  102.],
       [   1.,   -2.,   62.],
       [   1.,    3., -118.],
       [   1.,    5.,   82.],
       [   1.,    8., -118.]])

## Calculate regression coefficients

Now, calculate the regression coefficients.

The formula is

$
\mathbf{\hat{B}} = (\mathbf{X}\mathbf{X}^T)^{-1} \mathbf{X}^T \mathbf{y}
$

Let's calculate this step by step.

In [27]:
# X transpose
X_transpose = 
X_transpose

array([[   1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.],
       [   3.,   -1.,    9.,   -9.,    3.,    3.,    6.,   -7.,    3.,
           7.,    7.,    6.,    9.,   -7.,   -9.,   -1.,   -2.,    3.,
           5.,    8.],
       [ -38.,   22.,    2., -118.,  -78.,   42.,  162.,   22.,   82.,
        -178.,  -18.,  -58.,  142.,  122.,  -98.,  102.,   62., -118.,
          82., -118.]])

In [28]:
# X transpose * X
X_t_X = 
X_t_X

array([[  2.00000000e+01,   3.60000000e+01,   2.00000000e+01],
       [  3.60000000e+01,   7.32000000e+02,   3.72000000e+02],
       [  2.00000000e+01,   3.72000000e+02,   1.86000000e+05]])

In [29]:
# inverse of (X transpose * X)
# use np.linalg.inv
inverse = 

In [30]:
# multiply this inverse with X transpose
inverse_X_t = 
inverse_X_t

array([[  4.67825242e-02,   5.75426770e-02,   3.05768613e-02,
          7.91938500e-02,   4.68026576e-02,   4.67422573e-02,
          3.85890923e-02,   7.37282065e-02,   4.67221239e-02,
          3.60626382e-02,   3.59821045e-02,   3.86998262e-02,
          3.05063943e-02,   7.36778730e-02,   7.91837833e-02,
          5.75024102e-02,   6.02201319e-02,   4.68227910e-02,
          4.13269474e-02,   3.33348498e-02],
       [  1.90589948e-03,  -4.25738000e-03,   1.07984838e-02,
         -1.58792692e-02,   2.01431022e-03,   1.68907801e-03,
          5.86434332e-03,  -1.32583751e-02,   1.58066727e-03,
          8.28600043e-03,   7.85235748e-03,   6.46060238e-03,
          1.04190462e-02,  -1.35294019e-02,  -1.59334745e-02,
         -4.47420147e-03,  -5.86595658e-03,   2.12272095e-03,
          4.58099895e-03,   9.62355017e-03],
       [ -2.13143253e-04,   1.20606945e-04,  -1.41321140e-05,
         -6.11165532e-04,  -4.28416003e-04,   2.17402246e-04,
          8.55089691e-04,   1.36868556e-04

In [31]:
# now multiply this with y
B = 

array([ 30.,   3.,  -1.])

Now these are the intercept and the regression coefficients of our 2 predictors!