# Getting started with NumPy

In [2]:
import numpy as np

## Getting used to vectorization and broadcasting

First, let's generate some test data. Generate a two-dimensional array with 10 rows and 4 columns, from a normal distribution with mean = 100 and standard deviation 20.

In [3]:
data = np.random.normal(100, 20, (10,4))
data

array([[ 112.93505949,  114.97532889,   98.39136844,   98.92601584],
       [ 109.43399411,   85.82043372,   67.66757952,  100.64759196],
       [ 114.35031381,  109.94982874,  112.61943682,  118.36858443],
       [  55.67177024,  106.42902329,  104.49735834,  118.65223414],
       [ 109.25949316,  122.2448656 ,  112.68517231,   47.19511415],
       [ 103.73359692,   96.39851831,  111.37130165,   85.7556431 ],
       [ 101.44011346,  134.63383414,  114.75416097,  102.93011115],
       [  97.84970705,  123.95589594,  120.91753158,   73.84404592],
       [  75.19432009,   75.20696764,  104.37864122,  102.68267704],
       [ 139.26017858,   86.28058354,  122.12231962,   76.12275523]])

Round the data to one decimal place.

In [4]:
data = data.round(1)
data

array([[ 112.9,  115. ,   98.4,   98.9],
       [ 109.4,   85.8,   67.7,  100.6],
       [ 114.4,  109.9,  112.6,  118.4],
       [  55.7,  106.4,  104.5,  118.7],
       [ 109.3,  122.2,  112.7,   47.2],
       [ 103.7,   96.4,  111.4,   85.8],
       [ 101.4,  134.6,  114.8,  102.9],
       [  97.8,  124. ,  120.9,   73.8],
       [  75.2,   75.2,  104.4,  102.7],
       [ 139.3,   86.3,  122.1,   76.1]])

Display the last 2 columns of rows 1-5 (let's agree that we start counting from 1 when using normal language).

In [5]:
data[:5, -2:]

array([[  98.4,   98.9],
       [  67.7,  100.6],
       [ 112.6,  118.4],
       [ 104.5,  118.7],
       [ 112.7,   47.2]])

Now, set all data points > 130 to 0.

In [6]:
data = np.where(data > 130, 0, data)
data

array([[ 112.9,  115. ,   98.4,   98.9],
       [ 109.4,   85.8,   67.7,  100.6],
       [ 114.4,  109.9,  112.6,  118.4],
       [  55.7,  106.4,  104.5,  118.7],
       [ 109.3,  122.2,  112.7,   47.2],
       [ 103.7,   96.4,  111.4,   85.8],
       [ 101.4,    0. ,  114.8,  102.9],
       [  97.8,  124. ,  120.9,   73.8],
       [  75.2,   75.2,  104.4,  102.7],
       [   0. ,   86.3,  122.1,   76.1]])

Take the square root of all data points.

In [7]:
data = np.sqrt(data)
data

array([[ 10.62544117,  10.72380529,   9.91967741,   9.94484791],
       [ 10.45944549,   9.26282894,   8.22800097,  10.02995513],
       [ 10.69579357,  10.48332008,  10.61131472,  10.88117641],
       [  7.46324326,  10.31503757,  10.22252415,  10.89495296],
       [ 10.45466403,  11.05441088,  10.61602562,   6.87022561],
       [ 10.18331969,   9.81835017,  10.55461984,   9.26282894],
       [ 10.0697567 ,   0.        ,  10.71447619,  10.14396372],
       [  9.88938825,  11.13552873,  10.99545361,   8.59069264],
       [  8.67179336,   8.67179336,  10.21763182,  10.13410085],
       [  0.        ,   9.28977933,  11.04988688,   8.7235314 ]])

Now, compute the mean and the standard deviation over all data points.

In [8]:
mean, sd = np.mean(data), np.std(data)
mean, sd

(9.4468396662966789, 2.3763880826337394)

Then, compute the row means and standard deviations.

In [9]:
row_ms, row_sds = np.mean(data, axis=1), np.std(data, axis=1)
row_ms, row_sds

(array([ 10.30344295,   9.49505764,  10.66790119,   9.72393948,
          9.74883154,   9.95477966,   7.73204915,  10.15276581,
          9.42382984,   7.2657994 ]),
 array([ 0.3729121 ,  0.84786821,  0.14451342,  1.33041381,  1.67639006,
         0.47682481,  4.47106429,  1.0229108 ,  0.75261614,  4.28172384]))

Finally, compute column means and standard deviations.

In [10]:
col_ms, col_sds = np.mean(data, axis=0), np.std(data, axis=0)
col_ms, col_sds

(array([  8.85128455,   9.07548544,  10.31296112,   9.54762756]),
 array([ 3.10399127,  3.12338984,  0.76995644,  1.16310276]))

Now, compute the mean of column 2 without using NumPy's mean function.

In [12]:
data

array([[ 10.62544117,  10.72380529,   9.91967741,   9.94484791],
       [ 10.45944549,   9.26282894,   8.22800097,  10.02995513],
       [ 10.69579357,  10.48332008,  10.61131472,  10.88117641],
       [  7.46324326,  10.31503757,  10.22252415,  10.89495296],
       [ 10.45466403,  11.05441088,  10.61602562,   6.87022561],
       [ 10.18331969,   9.81835017,  10.55461984,   9.26282894],
       [ 10.0697567 ,   0.        ,  10.71447619,  10.14396372],
       [  9.88938825,  11.13552873,  10.99545361,   8.59069264],
       [  8.67179336,   8.67179336,  10.21763182,  10.13410085],
       [  0.        ,   9.28977933,  11.04988688,   8.7235314 ]])

In [13]:
col2 = data[:,1]
col2

array([ 10.72380529,   9.26282894,  10.48332008,  10.31503757,
        11.05441088,   9.81835017,   0.        ,  11.13552873,
         8.67179336,   9.28977933])

In [20]:
mean_col2 = col2.sum() / len(col2)
mean_col2

9.0754854350037224

In [21]:
var_col2 = ((col2 - mean_col2)**2).sum() / len(col2)
var_col2

9.7555641190353004

In [22]:
sd_col2 = np.sqrt(var_col2)
sd_col2

3.1233898442293913

Now double check again using NumPy's mean and std functions.

In [23]:
np.mean(col2)

9.0754854350037224

In [24]:
np.std(col2)

3.1233898442293913

In [25]:
((col2 - mean_col2)**2).sum()

97.555641190353001

## Linear regression from scratch

For practise with ndarrays and matrix operations, we are going to compute regression coefficients for linear regression ourselves.

First, let's create some data. We have measured 2 variables:

In [26]:
X = np.random.randint(-10,10,(20,2))
X

array([[  0,  -7],
       [  2,   3],
       [ -1,   9],
       [ -6,   2],
       [  5,   8],
       [ -1,   3],
       [  3,  -6],
       [ -4,   5],
       [  3,  -3],
       [ -5,   9],
       [ -7,   3],
       [  3,  -6],
       [ -2,  -4],
       [ -3, -10],
       [ -9,  -1],
       [ -5,   2],
       [ -5,   5],
       [  3,   5],
       [ -9,  -3],
       [ -5,   4]])

In [27]:
X[:,1] = X[:,1] * 20 + 2
X

array([[   0, -138],
       [   2,   62],
       [  -1,  182],
       [  -6,   42],
       [   5,  162],
       [  -1,   62],
       [   3, -118],
       [  -4,  102],
       [   3,  -58],
       [  -5,  182],
       [  -7,   62],
       [   3, -118],
       [  -2,  -78],
       [  -3, -198],
       [  -9,  -18],
       [  -5,   42],
       [  -5,  102],
       [   3,  102],
       [  -9,  -58],
       [  -5,   82]])

We want to predict a target variable y.
Of course, normally y would not be under our control ;-) But here, we are going to cheat ...

In [28]:
y = 30 + 3 * X[:,0] - X[:,1]
y

array([ 168,  -26, -155,  -30, -117,  -35,  157,  -84,   97, -167,  -53,
        157,  102,  219,   21,  -27,  -87,  -63,   61,  -67])

To calculate the regression coefficients, we need to add a column of ones to the input matrix.

In [29]:
ones = np.ones((20,1))
ones.ndim

2

In [30]:
X = np.append(ones, X, axis=1)
X

array([[   1.,    0., -138.],
       [   1.,    2.,   62.],
       [   1.,   -1.,  182.],
       [   1.,   -6.,   42.],
       [   1.,    5.,  162.],
       [   1.,   -1.,   62.],
       [   1.,    3., -118.],
       [   1.,   -4.,  102.],
       [   1.,    3.,  -58.],
       [   1.,   -5.,  182.],
       [   1.,   -7.,   62.],
       [   1.,    3., -118.],
       [   1.,   -2.,  -78.],
       [   1.,   -3., -198.],
       [   1.,   -9.,  -18.],
       [   1.,   -5.,   42.],
       [   1.,   -5.,  102.],
       [   1.,    3.,  102.],
       [   1.,   -9.,  -58.],
       [   1.,   -5.,   82.]])

## Calculate regression coefficients

Now, calculate the regression coefficients.

The formula is

$
\mathbf{\hat{B}} = (\mathbf{X}\mathbf{X}^T)^{-1} \mathbf{X}^T \mathbf{y}
$

Let's calculate this step by step.

In [31]:
# X transpose
X_transpose = X.T
X_transpose

array([[   1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.],
       [   0.,    2.,   -1.,   -6.,    5.,   -1.,    3.,   -4.,    3.,
          -5.,   -7.,    3.,   -2.,   -3.,   -9.,   -5.,   -5.,    3.,
          -9.,   -5.],
       [-138.,   62.,  182.,   42.,  162.,   62., -118.,  102.,  -58.,
         182.,   62., -118.,  -78., -198.,  -18.,   42.,  102.,  102.,
         -58.,   82.]])

In [32]:
# X transpose * X
X_t_X = X_transpose.dot(X)
X_t_X

array([[  2.00000000e+01,  -4.30000000e+01,   4.00000000e+02],
       [ -4.30000000e+01,   4.43000000e+02,  -1.58600000e+03],
       [  4.00000000e+02,  -1.58600000e+03,   2.44720000e+05]])

In [35]:
# inverse of (X transpose * X)
inverse = np.linalg.inv(X_t_X)

In [36]:
# multiply this inverse with X transpose
inverse_X_t = inverse.dot(X_transpose)
inverse_X_t

array([[  7.33355551e-02,   7.21086574e-02,   4.61879384e-02,
          2.54599836e-02,   8.34878659e-02,   5.41196714e-02,
          9.00025856e-02,   3.34867744e-02,   8.60367191e-02,
          2.22026237e-02,   1.81416994e-02,   9.00025856e-02,
          5.73770313e-02,   5.93124357e-02,   1.14368641e-02,
          3.14563122e-02,   2.74904457e-02,   7.54610751e-02,
          1.40807751e-02,   2.88124012e-02],
       [  4.78126768e-03,   1.22840158e-02,   4.72790531e-03,
         -1.08592408e-02,   2.17771801e-02,   3.67133054e-03,
          1.35700488e-02,  -4.58916317e-03,   1.40983362e-02,
         -6.75567509e-03,  -1.35540401e-02,   1.35700488e-02,
         -4.32235136e-04,  -4.35970501e-03,  -2.00002134e-02,
         -7.98834566e-03,  -7.46005827e-03,   1.55071025e-02,
         -2.03524050e-02,  -7.63615407e-03],
       [ -6.52791482e-04,   2.15098832e-04,   6.98852903e-04,
          5.96324400e-05,   6.66653569e-04,   1.88684463e-04,
         -5.41349039e-04,   3.32326240e-04

In [37]:
# now multiply this with y
inverse_X_t.dot(y)

array([ 30.,   3.,  -1.])

Now these are the intercept and the regression coefficients of our 2 predictors!