# Getting started with NumPy

In [1]:
import numpy as np

## Getting used to vectorization and broadcasting

First, let's generate some test data. Generate a two-dimensional array with 10 rows and 4 columns, from a normal distribution with mean = 100 and standard deviation 20.

In [2]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

Round the data to one decimal place.

In [ ]:
data = 
data

Display the last 2 columns of rows 1-5 (let's agree that we start counting from 1 when using normal language).

Now, set all data points > 130 to 0.

In [ ]:
data = 
data

Take the square root of all data points.

In [ ]:
data = 
data

Now, compute the mean and the standard deviation over all data points.

In [ ]:
mean, sd = 
mean, sd

Then, compute the row means and standard deviations.

In [ ]:
row_ms, row_sds = 
row_ms, row_sds

Finally, compute column means and standard deviations.

In [ ]:
col_ms, col_sds = 
col_ms, col_sds

Now, compute the mean and standard deviation of column 2 without using NumPy's mean function.

In [ ]:
data

In [ ]:
# take just column 2
col2 = 
col2

In [ ]:
# calculate the mean
mean_col2 = 
mean_col2

In [ ]:
# calculate the variance
var_col2 = 
var_col2

In [ ]:
# calculate the standard deviation
sd_col2 = 
sd_col2

Now double check again using NumPy's mean and std functions.

## Linear regression from scratch

For practise with ndarrays and matrix operations, we are going to compute regression coefficients for linear regression ourselves.

First, let's create some data. We have measured 2 variables:

In [4]:
X = np.random.randint(-10,10,(20,2))
X

array([[ -3,  -2],
       [  8,   4],
       [ -6,   6],
       [-10,  -1],
       [  4,   6],
       [  5,  -8],
       [ -6,   5],
       [ -2,   1],
       [  4,  -7],
       [  0,  -2],
       [ -7,   0],
       [  8,  -1],
       [  9, -10],
       [  4,  -9],
       [  4,   5],
       [ -3,   8],
       [  5,  -1],
       [ -1,  -8],
       [ -3,   4],
       [ -4,  -6]])

In [5]:
X[:,1] = X[:,1] * 20 + 2
X

array([[  -3,  -38],
       [   8,   82],
       [  -6,  122],
       [ -10,  -18],
       [   4,  122],
       [   5, -158],
       [  -6,  102],
       [  -2,   22],
       [   4, -138],
       [   0,  -38],
       [  -7,    2],
       [   8,  -18],
       [   9, -198],
       [   4, -178],
       [   4,  102],
       [  -3,  162],
       [   5,  -18],
       [  -1, -158],
       [  -3,   82],
       [  -4, -118]])

We want to predict a target variable y.
Of course, normally y would not be under our control ;-) But here, we are going to cheat ...

In [6]:
y = 30 + 3 * X[:,0] - X[:,1]
y

array([  59,  -28, -110,   18,  -80,  203,  -90,    2,  180,   68,    7,
         72,  255,  220,  -60, -141,   63,  185,  -61,  136])

To calculate the regression coefficients, we need to add a column of ones to the input matrix.

In [7]:
ones = np.ones((20,1))
ones

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [8]:
X = np.append(ones, X, axis=1)
X

array([[   1.,   -3.,  -38.],
       [   1.,    8.,   82.],
       [   1.,   -6.,  122.],
       [   1.,  -10.,  -18.],
       [   1.,    4.,  122.],
       [   1.,    5., -158.],
       [   1.,   -6.,  102.],
       [   1.,   -2.,   22.],
       [   1.,    4., -138.],
       [   1.,    0.,  -38.],
       [   1.,   -7.,    2.],
       [   1.,    8.,  -18.],
       [   1.,    9., -198.],
       [   1.,    4., -178.],
       [   1.,    4.,  102.],
       [   1.,   -3.,  162.],
       [   1.,    5.,  -18.],
       [   1.,   -1., -158.],
       [   1.,   -3.,   82.],
       [   1.,   -4., -118.]])

## Calculate regression coefficients

Now, calculate the regression coefficients.

The formula is

$
\mathbf{\hat{B}} = (\mathbf{X}\mathbf{X}^T)^{-1} \mathbf{X}^T \mathbf{y}
$

Let's calculate this step by step.

In [ ]:
# X transpose
X_transpose = 
X_transpose

In [ ]:
# X transpose * X
X_t_X = 
X_t_X

In [ ]:
# inverse of (X transpose * X)
# use np.linalg.inv
inverse = 

In [ ]:
# multiply this inverse with X transpose
inverse_X_t = 
inverse_X_t

In [ ]:
# now multiply this with y
B = 

Now these are the intercept and the regression coefficients of our 2 predictors!